# Generated by Django 6.0.7 on 2026-07-13 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["email"], "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
