# Generated by Django 6.0.7 on 2026-07-10 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_created_manually", models.BooleanField(default=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (10, "Not Scheduled"),
                            (20, "In Waiting List"),
                            (30, "Printing"),
                            (40, "Done"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("printer_name", models.CharField(default="Bambu Lab P1S", max_length=100)),
                ("state", models.CharField(max_length=255)),
                ("is_printing", models.BooleanField(default=False)),
                ("print_percentage", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_light_on", models.BooleanField(default=False)),
                ("wifi_signal_dbm", models.IntegerField(null=True)),
                ("temperature_nozzle", models.FloatField(null=True)),
                ("temperature_bed", models.FloatField(null=True)),
                ("temperature_chamber", models.FloatField(null=True)),
                (
                    "fan_speed_chamber",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(255),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "fan_speed_aux",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(255),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("chamber_image", models.ImageField(null=True, upload_to="storage/images/%Y/%m/%d/")),
                (
                    "project",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="printer_statuses",
                        to="storage.project",
                    ),
                ),
            ],
        ),
    ]
