# Generated by Django 6.0.7 on 2026-07-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printerstatus",
            name="printer_name",
        ),
        migrations.AlterField(
            model_name="printerstatus",
            name="chamber_image",
            field=models.ImageField(null=True, upload_to="core/chamber-images/"),
        ),
        migrations.AlterField(
            model_name="printerstatus",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printer_statuses",
                to="core.project",
            ),
        ),
    ]
