# Generated by Django 6.0.7 on 2026-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_printerstatus_printer_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printerstatus",
            old_name="state",
            new_name="printer_state",
        ),
        migrations.AddField(
            model_name="printerstatus",
            name="print_status",
            field=models.IntegerField(
                choices=[
                    (0, "Idle"),
                    (10, "Preparing"),
                    (20, "Running"),
                    (30, "Paused"),
                    (40, "Finished"),
                    (50, "Unknown"),
                    (60, "Failed"),
                ],
                default=50,
            ),
        ),
    ]
