# Generated by Django 6.0.7 on 2026-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_printerstatus_print_gcode_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printerstatus",
            name="print_status",
            field=models.IntegerField(
                choices=[
                    (0, "Printing"),
                    (1, "Auto_Bed_Leveling"),
                    (2, "Heatbed_Preheating"),
                    (3, "Sweeping_Xy_Mech_Mode"),
                    (4, "Changing_Filament"),
                    (5, "M400_Pause"),
                    (6, "Paused_Filament_Runout"),
                    (7, "Heating_Hotend"),
                    (8, "Calibrating_Extrusion"),
                    (9, "Scanning_Bed_Surface"),
                    (10, "Inspecting_First_Layer"),
                    (11, "Identifying_Build_Plate_Type"),
                    (12, "Calibrating_Micro_Lidar"),
                    (13, "Homing_Toolhead"),
                    (14, "Cleaning_Nozzle_Tip"),
                    (15, "Checking_Extruder_Temperature"),
                    (16, "Paused_User"),
                    (17, "Paused_Front_Cover_Falling"),
                    (18, "Calibrating_Lidar"),
                    (19, "Calibrating_Extrusion_Flow"),
                    (20, "Paused_Nozzle_Temperature_Malfunction"),
                    (21, "Paused_Heat_Bed_Temperature_Malfunction"),
                    (22, "Filament_Unloading"),
                    (23, "Paused_Skipped_Step"),
                    (24, "Filament_Loading"),
                    (25, "Calibrating_Motor_Noise"),
                    (26, "Paused_Ams_Lost"),
                    (27, "Paused_Low_Fan_Speed_Heat_Break"),
                    (28, "Paused_Chamber_Temperature_Control_Error"),
                    (29, "Cooling_Chamber"),
                    (30, "Paused_User_Gcode"),
                    (31, "Motor_Noise_Showoff"),
                    (32, "Paused_Nozzle_Filament_Covered_Detected"),
                    (33, "Paused_Cutter_Error"),
                    (34, "Paused_First_Layer_Error"),
                    (35, "Paused_Nozzle_Clog"),
                    (255, "Idle"),
                    (None, 40),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
