# Generated by Django 6.0.7 on 2026-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_printerdata_delete_printerstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="printerdata",
            name="current_layer_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="printerdata",
            name="subtask_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="printerdata",
            name="total_layers",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="printerdata",
            name="gcode_file_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
