# Generated by Django 6.0.7 on 2026-07-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_printerdata_current_layer_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printerdata",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Idle"),
                    (10, "Preparing"),
                    (20, "Running"),
                    (30, "Paused"),
                    (40, "Finished"),
                    (50, "Unknown"),
                    (60, "Failed"),
                ],
                default=50,
            ),
        ),
    ]
