# Generated by Django 6.0.7 on 2026-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_rename_printerdata_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to="core/projects/"),
        ),
    ]
