# Generated by Django 6.0.7 on 2026-09-16 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_project_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printerdata",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
