django-test:
  stage: test
  interruptible: true
  image: orbisk/django-test:3.13@sha256:5edf8883da9a1f474df7463c5d574b497235a2292e4fd52a8d09e98ef779874b
  extends:
    - .size:medium
  services:
    - postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
  variables:
    DJANGO_SETTINGS_MODULE: "printer_dashboard.settings.test"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
  script:
    - uv run coverage run manage.py test
    - uv run coverage report
    - uv run coverage xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?)\%$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-check:
  stage: test
  interruptible: true
  allow_failure: true
  image: orbisk/django-test:3.13@sha256:5edf8883da9a1f474df7463c5d574b497235a2292e4fd52a8d09e98ef779874b
  extends:
    - .size:medium
  variables:
    DJANGO_SETTINGS_MODULE: "printer_dashboard.settings.staging"
    DJANGO_SECRET_KEY: "not-very-secret-but-it's-fine-for-this-very-cool-deploy-check"
  script:
    - uv run manage.py check --deploy --fail-level DEBUG --force-color
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
      allow_failure:  false
