django-test:
  stage: test
  interruptible: true
  image: orbisk/django-test:3.13
  extends:
    - .size:medium
  services:
    - postgres:18@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
  variables:
    DJANGO_SETTINGS_MODULE: "printer_dashboard.settings.test"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
  script:
    - uv run manage.py test

deploy-check:
  stage: test
  interruptible: true
  allow_failure: true
  image: orbisk/django-test:3.13
  extends:
    - .size:medium
  variables:
    DJANGO_SETTINGS_MODULE: "printer_dashboard.settings.staging"
    DJANGO_SECRET_KEY: "not-very-secret-but-it's-fine-for-this-very-cool-deploy-check"
  script:
    - uv run manage.py check --deploy --fail-level DEBUG --force-color
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
      allow_failure:  false
